In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# df = pd.DataFrame()

In [107]:
df = df.append({'num_nodes': 8, "num_params": "2.5B", "average_throughput": 54.161, "sample_time_avg": 0.01846}, ignore_index = True)

In [108]:
df = df.sort_values(by=['num_nodes', 'num_params'])

In [109]:
df

    average_throughput  num_nodes num_params  sample_time_avg
0                6.498        1.0       2.5B         0.153900
1               42.570        1.0       250M         0.023490
2               80.081        1.0        25M         0.012490
3               13.482        2.0       2.5B         0.074170
4               80.546        2.0       250M         0.012420
5              156.657        2.0        25M         0.006383
6               27.133        4.0       2.5B         0.036860
7              158.595        4.0       250M         0.006305
8              307.445        4.0        25M         0.003253
25              54.161        8.0       2.5B         0.018460
9              305.066        8.0       250M         0.003278
10             576.249        8.0        25M         0.001735
11             565.139       16.0       250M         0.001769
12            1027.873       16.0        25M         0.000973
13             210.943       32.0       2.5B         0.004741
14             962.113       32.0       250M         0.001039
15            1641.973       32.0        25M         0.000609
16             396.310       64.0       2.5B         0.002524
17            1493.050       64.0       250M         0.000670
18            2275.963       64.0        25M         0.000439
19             727.133      128.0       2.5B         0.001375
20            2050.490      128.0       250M         0.000487
21            3226.762      128.0        25M         0.000310
22            1075.220      256.0       2.5B         0.000932
23            2416.772      256.0       250M         0.000416
24            3371.091      256.0        25M         0.000298

In [111]:
list(df[df['num_params'] == "2.5B"]['average_throughput'])

[6.498, 13.482, 27.133, 54.161, 210.943, 396.31, 727.133, 1075.22]

In [112]:
df.to_csv("initial_results.csv")